name: Build

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: sudo apt update && sudo apt install -yq libfontconfig1-dev

      - uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}

      - name: Cache ~/.cargo and target
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --release --locked --target ${{ matrix.target }}

      - name: Pack Artifacts
        env:
          ARTIFACT_NAME: dagtoc-${{ matrix.target }}
        run: |
          mkdir $ARTIFACT_NAME
          cp target/${{ matrix.target }}/release/dagtoc -t "$ARTIFACT_NAME"
          cp -r completions -t "$ARTIFACT_NAME"
          cp README.md LICENSE -t "$ARTIFACT_NAME"
          tar -zcvf "$ARTIFACT_NAME.tar.gz" -C "$ARTIFACT_NAME" .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dagtoc-${{ matrix.target }}.tar.gz
          path: dagtoc-${{ matrix.target }}.tar.gz

  release-draft:
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: [build-linux]
    steps:
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Release Draft
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            dagtoc-*.tar.gz
          generate_release_notes: true
