name: Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: sudo apt update && sudo apt install -yq libfontconfig1-dev

      - uses: dtolnay/rust-toolchain@stable

      - name: Cache ~/.cargo and target
        uses: Swatinem/rust-cache@v2

      - name: Clippy
        run: cargo clippy --all-features --all-targets -- -D warnings

  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Rustfmt
        run: cargo fmt --check
